# -*- coding: utf-8 -*-
"""algoritmos y programacion1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKVMvWJHFcUIwMupzjoYYPHpNVL_aEIt
"""

nombre = input   ( "Ingrese su usuario por favor" )
print   ( "Bienvenido" ,   nombre   , "espero que disfrute su estadia." )

print  ( "Bienvenido a la calculadora de la suma, ingrese su par de numeros a sumar" )
num1 =   float (  input  ())
num2 =   float (  input  ())
print   ( "El resultado de la suma es :" ,  num1 +num2  )

print  ( "Bienvenido a la calculadora de promedios, ingresa 5 notas y obtendras el promedio de tu materia" )
num1 =   float (  input  ())
num2 =   float (  input  ())
num3 =   float (  input  ())
num4 =   float (  input  ())
num5 =   float (  input  ())
print  (f"Su promedio es;",(num1+num2+num3+num4+num5  )/5 )

print("Bienvenido, inserte un número para conocer su cuadrado y cubo")
num1 = float(input())
print(f"El cuadrado del número equivale a: ",num1*num1)
print(f"El cubo del número equivale a: ",num1*num1*num1)

print  ( "Bienvenido, inserte la cantidad de dólares que quiere convertir a pesos" )
dls =   float (  input  ())
cnv = dls*  3.961
print  (f"la cantidad de dólares ingresados ​​a pesos colombianos a conversión del 12/08 /2023 equivale a" ,  cnv , "pesos colombianos")

dinero= int(input("ingre"))

x1= int(input("ingrese la valriable 1= "))
x2= int(input("ingrese la valriable 2= "))
x3= int(input("ingrese la valriable 3= "))
x1,x2,x3=x3,x1,x2
print("el valor de la segunda varibale es= ",x1)
print("el valor de la tercera variable es= ",x2)
print("el valor de la primera variable es= ",x3)

num= int(input("ingrese el numero que desea analizar: "))
if num%2==0 :
  print("el numero ingresado es par")
else:
    print("el numero ingresado es inpar")

num= int(input("ingrese el numero que desea analizar: "))
if num>0:
  print("el numero ingresado es positivo")
elif num==0:
    print("el numero ingresado es cero")
else:
  print("el numero es negativo")

password = input("ingrese la contraseña: ")

if (len(password) >= 8):
  print("tu contraseña es suficienteente larga")
  if(password == "miClaveSegura"):
    print("ademas la contraseña es correcta")
  else:
    print("pero es incorrecta")
else:
 print("tu contraseña es muy corta e insegura")
 if (password != "miClaveSegura"):
  print("tu clave es corta e insegura")
  print("ademas, es incorrecta (por supesto) ")

num= int(input("ingrese un numero:"))
if num%7==0 and num>40:
  print("El numero ingresado es divisible y mayor a 40")
else:
    print("el numero ingresado no es divisible o no es mayor a 40")

cat= (input("ingrese la categoria a la que pertenece el socio (A,B,C): "))
anti= int(input("ingrese su antiguedad en años: "))

if (cat=="A" or cat=="a")  or (anti<=20 and anti>=10)  :
  print("El socio es VIP")
else:
   print("El socio no es VIP")

import math
pi=math.pi

radio= int(input("Ingrese el radio del circulo para hallar el area y el volumen de la esfera: "))
if radio<=0:
  print("el numero ingresado es incorrecto, por favor ingrese un numero postivo")
  radio= int(input("Ingrese el radio del circulo para hallar el area y el volumen de la esfera: "))

a=pi*(radio**2)
v=(4/3*pi*(radio**3))
print("El area superficial segun el radio ingresado es: ",a,)
print("El volumen de la esfera segun el radio ingresado es: ",v,)

#Cuarto ejercicio python

valor= int(input("Ingrese el valor total de la compra para calcular el descuento: "))

if valor>=1:  ##condicionamos que la variable valor sea mayor a 1
  print("El valor ingresado es correcto")
else:         ##establecemos que si no se cumple nos pida de nuevo un valor positivo
  print("Por favor ingrese un valor positivo")
  valor=int(input("Ingrese el valor total de la compra para calcular el descuento: "))

rango=(input("Ingrese el rango del cliente (S,A,B): "))

S=0.15  #Establecemos los valores de los descuentos segun el rango
A=0.10  #Establecemos los valores de los descuentos segun el rango
B=0.05  #Establecemos los valores de los descuentos segun el rango

if rango =="A" or rango=="a" or rango=="B" or rango=="b" or rango=="S" or rango=="s": ##condicionamos que la variable sea igual a los caracteres ingresados
  print("La categoria ingresada es correcta")
else:                                                #Establecemos que si no se coincide nos pida de nuevo el rango al cual pertenece el cliente
  print("la categoria ingresada es incorrecta")
  rango=input("Ingrese el rango del cliente (S,A,B): ")


if (rango=="S" or rango=="s"):
  print("El valor con el descuento clase S es: ",valor+(-valor*S))  #Establecemos que si el caracter coincide con S Haga la operacion pertinente

if (rango=="A" or rango=="a"):
  print("El valor con el descuento clase A es: ",valor+(-valor*A))  #Establecemos que si el caracter coincide con A Haga la operacion pertinente

if (rango=="B" or rango=="b"):
  print("El valor con el descuento clase B es: ",valor+(-valor*B))  #Establecemos que si el caracter coincide con B Haga la operacion pertinente

audi= int(input("Ingrese la cantidad de audifonos a comprar: "))

valor=300
des1=0.15
des2=0.20

if audi>=1:
  print("el numero de audifonos ingresado es correcto")
else:
  print("el numero ingresado ni puede ser negativo o menor a 1,ingrese nuevamente: ")
  audi= int(input("Ingrese la cantidad de audifonos a comprar: "))

if audi>=1 and audi<=3:
  print("el costo de la compra de los",audi,"audifonos es:",audi*valor)

if audi>=4 and audi<=9:
  print("el costo de la compra de los",audi,"audifonos es:",audi*valor+(-audi*valor*des1))

if audi>9:
  print("el costo de la compra de los",audi,"audifonos es:",audi*valor+(-audi*valor*des2))

i = 0
while i < 5:
  print(i)
  i=1+i

z=8
x=1
while z>= 1:
  print('.' * z + '*' * x + '1' * z)
  x+=2
  z-=1

numero= int(input("ingrese un numero positivo: "))
while numero < 0:
  print("el numero no es positivo.")
  numero= int(input("ingrese un numero positivo: "))

numero_limite = int(input("Ingrese el numero limite: "))
suma = 0
numero_actual = 2

while numero_actual <= numero_limite:
  suma+= numero_actual
  numero_actual =+2

print("La suma de los numero es: ")

x=11
while x<=30:
  print(f"la raiz de {x} es {x**0.5}")
  x=x+1

numero_limites = int(input("Ingrese el numero limite para saber sus divisores: "))
n=1

while n<=numero_limites:
  if numero_limites%n==0:
    print(n)
  n = n+1

while True:
  print("estoy en u ciclo infinito. ")
  respuesta = input("¿Quieres salir? (s/n): ") #se coloca variable para comprobar y cambiar mayuscula a minuscula
  if respuesta.lower() == "s": #.lower/.higher es para cambiar el dato ingresado a minusucla o mayuscula
    print("Adios.")
    break #indica cuando se acaba el ciclo, fijarse en la sagria

saldo = 1000
continuar = True

while continuar:
  print("saldo actual: $" + str(saldo))
  opcion= input("¿Que deseas hacer? (Depositar/Retirar/Salir): ")

  if opcion == "Depositar":
    cantidad = float(input("Ingrese la cantidad a depositar: "))
    saldo += cantidad
  elif opcion == "Retirar":
    cantidad = float(inpu("Ingrese la cantidad a retirar: "))
    if cantidad <= saldo:
      saldo-=cantidad
    else:
      print("Saldo insuficiente.")
  elif opcion == "Salir":
    continuar = False
  else:
    print("Opcion no valida, intentalo de nuevo")

import random
numerosecreto = random.randint(1, 100)
intentos = 0
adivinanza = 0

while adivinanza != numerosecreto:
  adivinanza = int(input("Adivina el numero (entre 1 y 100): "))
  intentos +=1


  if adivinanza < numerosecreto:
    print("Demasiado bajo.")
  elif adivinanza > numerosecreto:
    print("Demasiado alto.")
  else:
    print("¡Correcto! ¡Has adivinado el numero en", intentos, "intentos!")

#a={0,1,2,3,4,5}
#a={ne N| n<= 5} #lo mismooooo

numeros = [1,2,3,4,5,6,7,8,9,10]
numeros_pares = [x for x in numeros if x % 2 == 0]
print ("Numeros pares:", numeros_pares)

a= [90, "PYTHON", 3.87]
print(a[0])
print(a[1])
print(a[2])
print(a[-1]) #ultimo -1 #penultimo -2 .....
#del 1 a [0]

L = [1,2,3,4,5,6]
print(L[0:2])
print(L[0:6])
print(L[-1:8])#no se puede ir hacia el sentido contrario
#l[0:3] = [0,0,0] se remplaza valores con rangos sin contar la ultima posicion de esta forma
#l = [1,2,3]
#l+= [4,5] operaciones entre listas
#l = [1,2,3]
#x,y,z = l
#print x,y,z
#l.append (3) agregaria este termino a la lista
#l.insert(1, 2) en el primer termino se especifica la posicion y en el segundo el termino a agregar
#l.remove("banano") o para numeros sin ""  (1) solamente elimina primer temino que se llame como "banano" en la lista
#l.pop(1)() por defecto elimina el ultmo elemento aunque se puede especificar cual se quiere eliminar
#l.reverse() ordena todos los valores al revez
#l.sort() ordena de menor a mayor, no roganiza letras solo listas numericas
#l.index("piña") identifica en que posicion esta ese termino en la lista siempre positivo no (-1"ultimo")

#FOOOOOR USO # la variable no hace falta definirla
for i in range(11,31): #range toma -1 valor del limite, en este caso es 30=31

  print(f"la raiz de {i} es {i**0.5}")

notas = []
n=int(input("cuantas notas para el promedio va a ingresar: "))

for i in range (n):
  nota = float(input(f"ingrese la nota {i+1} del curso: "))
  while nota<0 or nota>5:
    nota = float(input(f"la nota {i+1} ingresada es invalida, intente otra vez: "))
  notas.append(nota)

promedio = sum(notas)/len(notas)
print(f"El promedio del curso es {promedio}")



texto = input("Ingrese el texto a analizar: ")
palabra_buscada = input("ingrese la palabra que desea buscar sin espacios: ")

lista_texto = texto.split()

encontrado = False

for palabra in lista_texto:
  if palabra == palabra_buscada:
    encontrado = True
    break
if encontrado:
  print (f"{palabra_buscada} esta en el texto.")
else:
  print (f"{palabra_buscada} no esta en el texto.")

https://matplotlib.org/stable/gallery/lines_bars_and_markers/stackplot_demo.html#sphx-glr-gallery-lines-bars-and-markers-stackplot-demo-py

def y (v0,t):
  g=9.81 #variable local, no se utiliza fuera de ella
  return v0*t - 0.5*g*t**2

y(3,1) #La llamo con su nombre y establezco los dos argumentos o varibles que necesita para ejecutar la funcion

g=9.81
w= lambda v0,t: v0*t-0.5*g*t**2 #sirve para ejecutar una funcion simple en una sola linea

def numeropositivo(a):
  if a>0:
    return print ("el numero es negativo")
  elif a== 0:
    return print("el numero ingresado es 0")
  else:
    return print("el numero ingresado es positvo")

a=int(input("ingrese un numero: "))

#taller de estudio  for while taller
a= int

def factorial(d):

edad=int(input(" ingrese su edad: "))
e = 0
suma = 0

while e <= edad-1:
  suma: suma+e
  e+=1
  print("usted ha cumplido" ,e ,"años")

#suma números pares
n=1
suma=0
while n <= 100:
    if n % 2 ==0:
      suma = suma+n
    n+=1
print("la suma de los números pares del 1 al 100 es: ",suma)

n=0
suma=0

for n in range(1,101):
   if n % 2 == 0:
      suma= suma+n
print("la suma de los números pares del 1 al 100 es: ",suma)

num= int(input("Ingrese un numero: "))
fact=1
for i in range(1,num+1):
 fact*=i
print("el resultado factorial del número es: ",fact)

comprobar=True
while comprobar == True:
 n=int(input("ingresé un número entero positivo"))
 if n>0:
  comprobar== False
  for i in range(1,11):
    print(n, "por" ,i,":" ,n*i)
 else:
  print("por favor ingresé un número valido")

comp = True

while comp == True:
  for i in range(10,21):
   print(f"el cuadrado de {i} es {i**2}")
   print(f"el cubo de {i} es {i**3}")
  comp=False

  respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
  if respuesta.lower() == "s":
   comp=True
  else:
   comp=False

while True:

    cuadrado = []
    cubo = []


    for i in range(10,2):
        numero = float(input("Ingresa un número: "))
        cuadrado.append(numero ** 2)
        cubo.append(numero ** 3)


    print("Números ingresados:", cuadrado)
    print("Cuadrados:", cuadrado)
    print("Cubos:", cubo)


    respuesta = input("¿Deseas ejecutar el programa nuevamente? (s/n): ")

    # Salir del bucle si la respuesta es diferente de 's'
    if respuesta.lower() != 's':
        break

comp=True
comp2=True
while comp2==True:
  while comp==True:
    i=1
    a=1
    o=1
    sumanotas=0
    sumatotal=0
    parciales=5
    promedioestudiante=0
    promediogeneral=0
    alumnos=int(input("Ingrese la cantidad de alumnos: "))
    while (i<=alumnos):
      if alumnos >= 1:
        print("Ha ingresado un valor correcto")
        comp=False
        while o<=alumnos:
          for a in range(5):
            print("ingrese la nota numero ",a+1,"del alumno" ,o,)
            nota=float(input())
            sumanotas=sumanotas+nota
            sumatotal=sumatotal+nota
            promedioestudiante=sumanotas/parciales
            promediogeneral=promedioestudiante+promediogeneral
            a+=1
          print(f"El promedio de las notas de este alumno es: {promedioestudiante}")
          o+=1
        print(f"el promedio general de todos los alumnos es: {promediogeneral/alumnos} ")
        respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
        if respuesta.lower() == "s":
            comp2=True
            comp=True
        else:
            break
      else:
        print("Por favor ingrese un valor correcto")

comp2 = True
while comp2:
    comp = True
    i = 1
    parciales = 5
    promediogeneral = 0
    alumnos = int(input("Ingrese la cantidad de alumnos: "))

    if alumnos >= 1:
        print("Ha ingresado un valor correcto")
        comp = False

        while i <= alumnos:
            sumanotas = 0
            for a in range(5):
                print(f"Ingrese la nota número {a+1} del alumno {i}:")
                nota = float(input())
                sumanotas += nota
                promedioestudiante = sumanotas / parciales
                promediogeneral += promedioestudiante
            print(f"El promedio de las notas del alumno {i} es: {promedioestudiante}")
            i += 1

        print(f"El promedio general de todos los alumnos es: {promediogeneral / alumnos}")

        respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
        if respuesta.lower() == "s":
            comp2 = True
        else:
            break
    else:
        print("Por favor ingrese un valor correcto")

sumapf=0
sumapm=0
sumas1=0
sumas2=0
sumae=0
edad=0
i=1
estudi=int(input("Ingrese la cantidad de estudiantes: "))
for i in range(estudi):
  print(f"ingrese la edad del estudiante {i+1} : ")
  edad=int(input())
  sumae=sumae+edad
  print(f"ingrese el sexo del estudiante {i+1} (f/m): ")
  sexo=(input())
  if sexo=="f":
   sumas1=sumas1+1
   print(f"ingrese el peso de la estudiante {i+1} en kg: ")
   pesof=float(input())
   sumapf+=pesof
  else:
   sumas2=sumas2+1
   print(f"ingrese el peso del estudiante {i+1} en kg: ")
   pesom=float(input())
   sumapm+=pesom

  if i+1==estudi:
    print(f"El promedio de edad de los participantes: {sumae/estudi}")
    print(f"El promedio de peso de los hombres es: {sumapm/estudi}")
    print(f"El promedio de peso de las mujeres es: {sumapf/estudi}")
    print(f"el numero de hombres en el curso {sumas2}")
    print(f"el numero de mujeres en el curso {sumas1}")

numeros = []

i = 0
while i<10000:
    i+=1
    if i%2 != 0:
        numeros.append(i)
print(sum(numeros))

sum=0
for i in [1,2,3,4,5,6,7,8,9,10]:
 sum = sum + i
print("sum: ", sum)

comp = True

while comp == True:
  for i in range(10,21):
   print(f"el cuadrado de {i} es {i**2}")
   print(f"el cubo de {i} es {i**3}")
  comp=False

  respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
  if respuesta.lower() == "s":
   comp=True
  else:
   comp=False

def puntuacion(clase):
  return sum(clase)/ len (clase)

clase=[7,8,9]
media= puntuacion(clase)
print("La puntuacion de esta clase: ",media)

clase=[5,6,7.2,10]
media= puntuacion(clase)
print("La puntuacion de esta clase: ",media)

num=int(input("ingrese un numero para saber su tabla de multiplicar: "))
def mostrar_linea(num,linea):
  print(num, "x", linea, "=>" ,num * linea)

mostrar_linea(num,1)
mostrar_linea(num,2)
mostrar_linea(num,3)
mostrar_linea(num,4)
mostrar_linea(num,5)
mostrar_linea(num,6)
mostrar_linea(num,7)
mostrar_linea(num,8)
mostrar_linea(num,9)
mostrar_linea(num,10)

participantes=["Elena","Raúl","Jonathan","Pepe","Ana"]
print("primera posición", participantes [0])
print("primera posición", participantes [1])
print("primera posición", participantes [2])
print("primera posición", participantes [3])
print("primera posición", participantes [4])

(Listo+listo)las suma
print[10 in list1]
lista.insert(2,3) lo agrega al final
lista.index()
Lista.count()
Listo.pop()
Listo.remove(3)
Listo.reverse()
Listo.sort()
For elemento un frutas:
 Print(elemento)

suma=0
promedio=0
comp=True
while comp:#Repetir en caso de que la respuesta sea s
 estudi=int(input("Ingrese la cantidad de alumnos: "))#Se pide la cantidad de estudiantes a ingresar
 if estudi>0:
  i=1
  for i in range(estudi):
    a=1
    for a in range(5):
      (print(f"ingrese la nota numero {a+1} del alumno {i+1}"))
      nota=float(input())
      suma+=nota
      a+=1
    promedio=suma/5
    print(f"El promedio de las notas de este alumno es: {promedio}")
    i+=1
  print(f"el promedio general de todos los alumnos es: {promedio/estudi} ")
  respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
  if respuesta.lower() == "s":
    comp=True
  else:
    break

comp = True

while comp == True:
  for i in range(10,21):
   print(f"el cuadrado de {i} es {i**2}")
   print(f"el cubo de {i} es {i**3}")
  respuesta = input("¿Quieres ejecutar el programa de nuevo? (s/n): ")
  if respuesta.lower() == "s":
   comp=True
  else:
   comp=False

print("Ingrese un numero: ")
N=int(input())
i=0
num=0
a=0
b=1

if N==1:
  print("0")
elif N==2:
  print("1")

for i in range(N):
  print(a)
  num=a
  a=b
  b=b+num

  i+=1

print("Ingrese el valor de la compra: ")
valor=float(input())
solictar_valor(valor)

def solictar_valor(valor):
  if valor>=645000:
    descuento1=valor*0.10
    valordescon=valor-descuento1

  else:
    descuento2=valor*0.03
    valordescon=valor-descuento2
  print(f"el valor total es: {valordescon}")

  def solicitar_valordescuento(valordescon):
    if valor>400000:
      descuento3=valor*0.05
      print("tienes un descuento adicional del 5%")
  print(f"el valor total es: {valordescon}")

print("Ingrese la cantidad de segundos sin fracciones: ") #Le especifico al usuario que ingrese la cantidad de segundos sin fracciones
segundos=int(input())         #Esta variable guardara la cantidad de segundos ingresados por el usuario
calculo_de_correspondencia_segundos(segundos)  #Llamo a la funcion

def calculo_de_correspondencia_segundos(segundos):  #Defino la funcion y le digo que el valor con el que operara sera la variable segundos
  horas=segundos//3600    #Horas sera la division entera entre los segundos ingresados y 3600(cantidad de segundos que tiene una hora)
  sobrante1=segundos%3600  #Guardo el sobrante de la division en sobrante1 con la funcion modulo
  minutos=sobrante1//60   #Divido el sobrante de la division en 60 que es la cantidad de segundo que tiene un minuto
  segundosob=sobrante1%60  #El sobrante de la variable sobrante1 sera la cantidad de segundos restantes y lo guardo en la variable segundosob
  print(f"las horas son: {horas}")
  print(f"los minutos son: {minutos}")
  print(f"las segundos son: {segundosob}")